### ISSUE TITLE
Issues running the script on macOS 12.4 (MBP M1)

### ISSUE THREAD

**Issue by forsgren** [snicker/gyroscope2gpx#1]
I'm getting the following error message when trying to run the script:

```shell 
python3 gyroscope2gpx.py gyroscope-travels-export.csv 
INFO:__main__:Loading input csv...
/opt/homebrew/lib/python3.9/site-packages/dateparser/date_parser.py:35: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  date_obj = stz.localize(date_obj)
INFO:__main__:Done.
INFO:__main__:Grouping Gyroscope data into segments...
INFO:__main__:Done.
Traceback (most recent call last):
  File "/Downloads/gyroscope2gpx-master/gyroscope2gpx.py", line 127, in <module>
    main()
  File "/Downloads/gyroscope2gpx-master/gyroscope2gpx.py", line 111, in main
    filename = os.path.join(args.outputdir,basename)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Any obvious thing I'm missing? Can I contribute with any more information to sort it out?

**Comment by forsgren** [comment]
Update: Works if I try to run it a second time. Might be related to the output directory not being created the first run

Output on second run:

```shell
python3 gyroscope2gpx.py gyroscope-travels-export.csv
INFO:__main__:Loading input csv...
/opt/homebrew/lib/python3.9/site-packages/dateparser/date_parser.py:35: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  date_obj = stz.localize(date_obj)
INFO:__main__:Done.
INFO:__main__:Grouping Gyroscope data into segments...
INFO:__main__:Done.
INFO:__main__:Writing ./gyroscope2gpx_output/20220729_gyroscope.gpx...
[the rest of the output files goes here]
```
